sudo: false
language: python
cache: pip
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - travis_retry pip install tox-travis
script:
  - tox
after_success:
  coveralls

matrix:
  allow_failures:
  - python: 3.6  # FIXME
